# Generated by Django 5.0.7 on 2024-11-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_follow_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="dateofcontent",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
