# Generated by Django 5.0.7 on 2024-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_post_dateofcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="number_of_likes",
            field=models.IntegerField(default=0),
        ),
    ]
